from jaxrl2.wrappers.dmc2gym import DMC2GYM
from jaxrl2.wrappers.flatten_action_space import FlattenAction
from jaxrl2.wrappers.frame_stack import FrameStack
from jaxrl2.wrappers.gym import wrap_gym
from jaxrl2.wrappers.pixels import wrap_pixels
from jaxrl2.wrappers.repeat_action import RepeatAction
from jaxrl2.wrappers.single_precision import SinglePrecision
from jaxrl2.wrappers.universal_seed import UniversalSeed
from jaxrl2.wrappers.video_recorder import VideoRecorder
